
service: new-exercise-serverless-lambda

provider:
  name: aws
  runtime: nodejs14.x
  #lambdaHashingVersion: 20201221
  stage: dev
  region: ap-southeast-2

functions:
  generateRandomNumber:
    handler: src/handler.generateRandomNumber
